# Generated by Django 4.1.1 on 2022-09-18 04:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('latitude', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('appointment_desc', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(96)])),
                ('end_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(96)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psw.client')),
                ('psw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psw.psw')),
            ],
        ),
    ]
