# Generated by Django 4.1.1 on 2022-09-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
