# Generated by Django 4.1.1 on 2022-09-17 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(96)])),
                ('end_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(96)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psw.client')),
                ('psw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psw.psw')),
            ],
        ),
        migrations.AddField(
            model_name='psw',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='psw.scheduleitem'),
        ),
    ]
