# Generated by Django 4.1.1 on 2022-09-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0005_alter_psw_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='psw',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=43.470604, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psw',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-80.527239, max_digits=9),
            preserve_default=False,
        ),
    ]
