# Generated by Django 4.1.1 on 2022-09-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0006_psw_latitude_psw_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psw',
            name='schedule',
        ),
    ]
