# Generated by Django 4.1.1 on 2022-09-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0007_remove_psw_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='completed',
        ),
    ]
